# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# no PR triggers
pr: none
trigger:
- npm-test
pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- script: |
    npm install
    npm run build   
  displayName: 'npm install and build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      if [[ npm install and build == succeeded ]]; then
              echo “Success”
            else
              echo “Failure,exit status $?”
            fi
     


- task: Bash@3
  inputs: 
    targetType: 'inline'
    script: |
      echo '//registry.npmjs.org/:_authToken=$(TOKEN)' > .npmrc
      echo '[Action] logging package files'
      ls     
      git stash 
      git config --global user.email "karthicksettu52@gmail.com"
      git config --global user.name "Sk1810"
      npm version patch -m "Bump version to %s [skip ci]" --force
      git push origin HEAD:$(Build.SourceBranchName)
      npm publish
      
    workingDirectory: '.'


